---
title: "A Functional Neuroimaging Investigation of Moral Foundations Theory"
output: 
editor_options: 
  chunk_output_type: console
---

```{r load packages}
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)
library(performance)
library(devtools)
library(ggpubr)
library(ggeffects)
library(sjPlot)
library(RColorBrewer)
library(paletti)
library(patchwork)
library(ggcorrplot)
library(extrafont)
```

# Global variables, functions, etc
```{r custom global things}
se <- function(x) sqrt(var(x)/length(x))
`%notin%` <- Negate(`%in%`)
emm_options(lmerTest.limit = 5000)
emm_options(pbkrtest.limit = 5000)

# assign OG & new superordinate category
superordinateCategory <- function(c) {
  return(ifelse(c == 'Harm-Emo', 'Individualizing',
         ifelse(c == 'Harm-Phys', 'Individualizing',
         ifelse(c == 'Fairness', 'Individualizing',
         ifelse(c == 'Loyalty', 'Binding',
         ifelse(c == 'Authority', 'Binding',
         ifelse(c == 'Purity', 'Binding', as.character(c))))))))
}

superordinateNew <- function(c) {
  return(ifelse(c == 'Harm-Emo', 'Emotion',
         ifelse(c == 'Harm-Phys', 'Emotion',
         ifelse(c == 'Loyalty', 'Not Emotion',
         ifelse(c == 'Authority', 'Not Emotion',
         ifelse(c == 'Purity', 'Emotion', 
         ifelse(c == 'Liberty', 'Not Emotion', as.character(c))))))))
}

# getting var names straightened out 
assignCategory <- function(c) {
  return(ifelse(substr(c, 1,4) == 'auth', 'Authority', 
         ifelse(substr(c, 1,7) == 'careemo', 'Harm-Emo', 
         ifelse(substr(c, 1,8) == 'carephys', 'Harm-Phys', 
         ifelse(substr(c, 1,4) == 'fair', 'Fairness', 
         ifelse(substr(c, 1,3) == 'lib', 'Liberty', 
         ifelse(substr(c, 1,3) == 'loy', 'Loyalty',
         ifelse(substr(c, 1,3) == 'pur' , 'Purity', 
         ifelse(substr(c, 1,7) == 'socnorm', 'Social Norms', NA)))))))))
}
plotting_categories <- c('Social Norms', 
                         'Authority', 'Loyalty', 'Purity', 
                         'Harm-Emo', 'Harm-Phys', 'Fairness', 
                         'Liberty')

matlab_categories <- c('Authority', 'Harm-Emo', 'Harm-Phys', 'Fairness', 'Liberty', 
                       'Loyalty', 'Purity', 'Social Norms')

# contrasts 
SuperordinateContrasts <- list(LibertyVsSocial=c(-1, 0, 0, 0, 0, 0, 0, 1),
                BindingVsSocial=c(-1, 1/3, 1/3, 1/3, 0, 0, 0,0),
                IndividualizingVsSocial=c(-1, 0, 0, 0, 1/3, 1/3, 1/3, 0),
                LibertyVsBinding=c(0, -1/3, -1/3, -1/3, 0, 0, 0, 1),
                LibertyVsIndividualizing=c(0, 0, 0, 0, -1/3, -1/3, -1/3, 1),
                IndividualizingVsBinding=c(0, 0, -1/3, -1/3, -1/3, 1/3, 1/3, 1/3))

newSuperordinateContrasts <- list(FairnessVsSocial=c(-1, 0, 0, 0, 0, 0, 1, 0),
                EmotionVsSocial=c(-1, 0, 0, 1/3, 1/3, 1/3, 0, 0),
                NotEmotionVsSocial=c(-1, 1/3, 1/3, 0, 0, 0, 0, 1/3),
                EmotionVsNotEmotion=c(0, -1/3, -1/3, 1/3, 1/3, 1/3, 0, -1/3),
                EmotionVsFairness=c(0, 0, 0, 1/3, 1/3, 1/3, -1, 0),
                NotEmotionVsFairness=c(0, 1/3, 1/3, 0, 0, 0, -1, 1/3))

old_superordinate <- function(levels) {
  if (length(levels) == 8) {
    return(as.data.frame(SuperordinateContrasts))
  }
  return(NULL)
}

new_superordinate <- function(levels) {
  if (length(levels) == 8) {
    return(as.data.frame(newSuperordinateContrasts))
  }
  return(NULL)
}

# custom color palette
## shoutout https://edwinth.github.io/blog/paletti/ for the elegant paletti method of doing this
## https://learnui.design/tools/data-color-picker.html used for generating the gradients, but I heavily tweaked the default output
colors <- c('#c179f7', '#c40233', '#E60026','#ea3c53', '#2b8cd6', '#86b1e4','#bfd2f2','#7CAE00')
#viz_palette(colors) - uncomment to visualize palette
mem_colors <- c('#c179f7', '#c40233', '#E60026','#ea3c53', '#2b8cd6', '#86b1e4','#bfd2f2','#7CAE00',
                '#c179f7', '#c40233', '#E60026','#ea3c53', '#2b8cd6', '#86b1e4','#bfd2f2','#7CAE00')
#viz_palette(mem_colors)
MFT_fill  <- get_scale_fill(get_pal(colors))
MFT_color <- get_scale_color(get_pal(colors))
MFT_memfill <- get_scale_fill(get_pal(mem_colors))
MFT_memcol <- get_scale_color(get_pal(mem_colors))
```


```{r Load in data}
# load encoding data
encodingfiles = list.files('data/behavior/encoding', full.names = TRUE, pattern = '.csv', recursive = FALSE)
encodingFull = do.call(rbind, lapply(encodingfiles, function(x){read.csv(x, header = TRUE, stringsAsFactors = FALSE)}))

# load retrieval data
retfiles = list.files('data/behavior/retrieval', full.names = TRUE, pattern = '.csv', recursive = FALSE)
retFull = do.call(rbind, lapply(retfiles, function(x){read.csv(x, header = TRUE, stringsAsFactors = FALSE)}))

# load vignette key
key <- read.csv('data/key.csv', stringsAsFactors = FALSE)
```

```{r Tidy data & analysis prep}
# tidy encoding
envars <- names(encodingFull) %in% c('run','pres_order','vignum','trialstart_raw','trialstart_zeroed','trialstart_TR','trialdur','intended_jitter','ITI_start_raw','ITI_start_zeroed','ITI_start_TR','ITI_duration','ITI_accuracy', 'foundation', 'vigtext') 
encoding_behav <- encodingFull[!envars]
encoding_behav <- filter(encoding_behav, vigfile != 99999)
#get rid of '.jpg' suffix
encoding_behav <- as.data.frame(sapply(encoding_behav, function(x) gsub(".jpg", "", x)), stringsAsFactors = FALSE) 
names(encoding_behav)[4]<-"encoding_RT"
#get rid of symbols, quotation marks, & any white space
encoding_behav$moral_decision <- as.numeric(encoding_behav$moral_decision)
encoding_behav <- as.data.frame(sapply(encoding_behav, function(x) gsub("^\t* *\"* *| *\"* *\t*$", "", x)), stringsAsFactors = FALSE) 

# tidy key
key <- as.data.frame(sapply(key, function(x) gsub("^\t* *\"* *| *\"* *\t*$", "", x)), stringsAsFactors = FALSE)
key <- subset(key, select = -c(correct_answer, choice1, choice2, choice3)) #delete extra columns

# tidy retrieval
ret_all <- retFull
ret_all$resp <- sapply(ret_all$resp, function(s) as.numeric(substr(s, 1, 2))) #get rid of symbols
ret_all$confresp <- sapply(ret_all$confresp, function(s) as.numeric(substr(s, 1, 2))) #get rid of symbols
ret_all <- as.data.frame(sapply(ret_all, function(x) gsub("^\t* *\"* *| *\"* *\t*$", "", x)), stringsAsFactors = FALSE) #get rid of quotation marks & any white space
ret_all <- left_join(ret_all, key) #make column with category for each cue
ret_all$old <- as.numeric(substr(ret_all$category, 1,4) != 'Lure') #add old/new status of each item
ret_all$category <- sapply(ret_all$category, function(x) gsub("Lure-", "", x)) #get rid of 'Lure-' prefix
ret_all$vigfile[ret_all$vigfile == ''] = NA
names(ret_all)[8]<-"retrieval_RT"

# determine which subjects I have all data for
sort(as.numeric(levels(as.factor(encoding_behav$subID))))
sort(as.numeric(levels(as.factor(ret_all$subID)))) 
## missing encoding data for sub 35
## missing retrieval data for sub 36

# one big happy dataframe
encoding <- subset(encoding_behav, encoding_behav$subID %in% ret_all$subID) # subset of encoding files that have corresponding retrieval files
retrieval <- subset(ret_all, ret_all$subID %in% encoding_behav$subID) # subset of retrieval files that have corresponding encoding files
data <- merge(retrieval, encoding, by=c('subID', 'vigfile'), all.x = TRUE) # congolomerate of these 
#sort(as.numeric(levels(as.factor(encoding_behav$subID))))
#sort(as.numeric(levels(as.factor(data$subID))))
#sort(as.numeric(levels(as.factor(all_other_surveys$subID))))
dataN = length(levels(as.factor(data$subID)))
dataSubs = sort(as.numeric(levels(as.factor(data$subID))))
#qualtricsSubs = sort(as.numeric(levels(as.factor(all_other_surveys$subID)))) 
## missing qualtrics data for sub 20

# homogenize variable names
data$category[data$category == "SN"] <- "Social-Norms"
data$category[data$category == "Lib"] <- "Liberty"
data$category[data$category == "Loy"] <- "Loyalty"
data$category[data$category == "Pure"] <- "Purity"
data$category[data$category == "Auth"] <- "Authority"
data$category[data$category == "Fair"] <- "Fairness"
data$category[data$category == "Social-Norms"] <- "Social Norms"
data$category[data$category == "Care-Phys"] <- "Harm-Phys"
data$category[data$category == "Care-Emo"] <- "Harm-Emo"

# make text-based response column; new responses = NA
data$text_response = ''
i = 0
for (n in data$resp) {
  i = i + 1
  if (is.na(n) == TRUE) {                       
    data$text_response[i] = NA
  } else if (n == 1) {
    data$text_response[i] = data$choice1[i]
  } else if (n == 2) {
    data$text_response[i] = data$choice2[i]
  } else if (n == 3) {
    data$text_response[i] = data$choice3[i]
  } else {
    data$text_response[i] = NA
  }
} 

# make column for modeling proportion correct
data$correct <- as.numeric((!is.na(data$text_response) & data$text_response == data$correct_answer) |
  (is.na(data$text_response) & data$old == 0))

# make columns with superordinate categories
data$superordinate = (superordinateCategory(data$category))
data$superordinate_new = (superordinateNew(data$category))
data$superordinate <- factor(data$superordinate, levels = c('Social Norms', 'Liberty', "Individualizing", "Binding"))
data$superordinate_new <- factor(data$superordinate_new, levels = c('Social Norms', 'Fairness', 'Emotion', 'Not Emotion'))


# convert RTs & moral judgment to numeric
RT_cols <- c(9,11,15)
data[, RT_cols] <- data %>% select(ends_with('RT')) %>% sapply(as.numeric)
data <- data %>% filter(retrieval_RT > 0.25) %>%
  filter(confRT > 0.25) %>%
  mutate(moral_decision=as.numeric(moral_decision),
         confresp=as.numeric(confresp),
         category=factor(category, levels=plotting_categories),
         old=factor(old, levels = c('1', '0')))

# make encoding/moral judgment dataframe
data_old <- subset(data, old == '1' & encoding_RT > 0.25)

# for behavioral analyses and plotting
data <- data %>% group_by(subID, category, old) %>% mutate(propCorrect = mean(correct)) %>% ungroup() # so that violin plots can reflect participant response densities
confLabels <- c('1' = 'Correct', '0' = 'Incorrect')
memLabels <- c('1' = 'Old', '0' = 'New')
```

# PLS plots
```{r prep for PLS}
# task PLS 
mean_brain_scores <- read.csv('data/PLS/mean-centered/brain_scores.csv')
mean_brain_scores$category <- matlab_categories
mean_brain_scores$superordinate <- superordinateCategory(mean_brain_scores$category)
upper_CIs <- read.csv('data/PLS/mean-centered/upper_CIs.csv')
lower_CIs <- read.csv('data/PLS/mean-centered/lower_CIs.csv')
colnames(upper_CIs) <- paste0('upper_', colnames(upper_CIs))
colnames(lower_CIs) <- paste0('lower_', colnames(lower_CIs))
mean_centered_results_LV1 <- select(mean_brain_scores, category, superordinate, LV1)
mean_centered_results_LV1$upper <- upper_CIs$upper_LV1
mean_centered_results_LV1$lower <- lower_CIs$lower_LV1
mean_centered_results_LV1$category <- factor(mean_centered_results_LV1$category, 
                                             levels=plotting_categories)

mean_centered_results_LV2 <- select(mean_brain_scores, category, superordinate, LV2)
mean_centered_results_LV2$upper <- upper_CIs$upper_LV2
mean_centered_results_LV2$lower <- lower_CIs$lower_LV2
mean_centered_results_LV2$category <- factor(mean_centered_results_LV2$category, 
                                             levels=plotting_categories)
# task temporal brain score data
LV1 <- read.csv('data/PLS/mean-centered/temporal_brainscores_LV1_all.csv')
LV2 <- read.csv('data/PLS/mean-centered/temporal_brainscores_LV2_all.csv')
LV1$subID <- rep(dataSubs, each = 8)
LV2$subID <- rep(dataSubs, each = 8)
LV1$category <- matlab_categories
LV2$category <- matlab_categories

LV1 <- pivot_longer(LV1, cols = starts_with('Lag'), names_to = 'lag', values_to = 'score')
LV2 <- pivot_longer(LV2, cols = starts_with('Lag'), names_to = 'lag', values_to = 'score')

# task non-rotated data -- commented out because we're not reporting plots for this analysis
# nr_social <- read.csv('data/PLS/results/non-rotated/socialnorms_means.csv', header = FALSE)
# nr_social_upper <- read.csv('data/PLS/results/non-rotated/socialnorms_upper.csv', header = FALSE)
# nr_social_lower <- read.csv('data/PLS/results/non-rotated/socialnorms_lower.csv', header = FALSE)
# nr_social$upper <- nr_social_upper$V1
# nr_social$lower <- nr_social_lower$V1
# nr_social$category <- matlab_categories
# nr_social$category <- factor(nr_social$category, levels = plotting_categories)
# 
# nr_superordinate <- read.csv('data/PLS/results/non-rotated/superordinate_means.csv', header = FALSE)
# nr_superordinate_upper <- read.csv('data/PLS/results/non-rotated/superordinate_upper.csv', header = FALSE)
# nr_superordinate_lower <- read.csv('data/PLS/results/non-rotated/superordinate_lower.csv', header = FALSE)
# nr_superordinate$upper <- nr_superordinate_upper$V1
# nr_superordinate$lower <- nr_superordinate_lower$V1
# nr_superordinate$category <- matlab_categories[1:7]
# nr_superordinate$category <- factor(nr_superordinate$category, levels = plotting_categories[2:8])
```

# Emotion analyses
```{r emotion & empathy analyses}
### prep for emotion & empathy comparison
# Emotion responses
emotion_rating <- read.csv('data/behavior/qualtrics/emotion_ratings.csv', stringsAsFactors = FALSE)
emotion_rating[2:30, 2:721] <- as.data.frame(sapply(emotion_rating[2:30, 2:721], function(s) substr(s, 1, 2)), stringsAsFactors = FALSE)
names(emotion_rating)[1] <- 'subID'
emotion_rating <- emotion_rating[2:nrow(emotion_rating),] %>% pivot_longer(2:ncol(emotion_rating), names_to=c('vigfile', 'emotion'), names_pattern='([a-z]+\\d+)\\.*(.*)' , values_to='emoresp')
emotion_rating$emotion[emotion_rating$emotion == ''] = 'angry'
emotion_rating$emotion[emotion_rating$emotion == '1'] = 'sad'
emotion_rating$emotion[emotion_rating$emotion == '2'] = 'disgusted'
emotion_rating$emotion[emotion_rating$emotion == '3'] = 'afraid'
emotion_rating$emotion[emotion_rating$emotion == '4'] = 'contemptuous'
emotion_rating$emotion[emotion_rating$emotion == '5'] = 'amused'
emotion_rating$emoresp <- as.numeric(emotion_rating$emoresp)
emotion_rating <- subset(emotion_rating, subID != c('20', '35', '36'))
# emotion_rating_pls <- pivot_wider(emotion_rating, names_from = emotion, values_from = emoresp)


emotion_rating$category <- assignCategory(emotion_rating$vigfile)
emotion_rating$category <- factor(emotion_rating$category, levels = plotting_categories)

# load & prep empathy dataframe
all_other_surveys <- read.csv('data/behavior/qualtrics/all_other_surveys.csv', stringsAsFactors = FALSE)
iri <- select(all_other_surveys, starts_with('sub'), starts_with('iri'))
# score iri
iri <- as.data.frame(sapply(iri, function(s) substr(s, 1, 2)), stringsAsFactors = FALSE)
colnames(iri) <- substr(colnames(iri), 5, 7)
iri <- as.data.frame(sapply(iri, function(x) gsub("^\t* *\"* *| *\"* *\t*$", "", x)), stringsAsFactors = FALSE)
names(iri)[1] <- 'subID'
iri <- iri[-1,]
iri[iri == 'A' ] <- 0
iri[iri == 'B' ] <- 1
iri[iri == 'C' ] <- 2
iri[iri == 'D' ] <- 3
iri[iri == 'E' ] <- 4
iri[,2:29] <- as.numeric(unlist(iri[,2:29]))
reverseScoredIRI <- c('3', '4', '7', '12', '13', '14', '15', '18', '19')
iri[,reverseScoredIRI] <- 4 - (iri[,reverseScoredIRI])
#subscale coding
perspective_taking <- c('3','8','11','15','21','25','28')
fantasy <- c('1', '5', '7','12','16','23','26')
empathic_concern <- c('2','4','9','14','18','20','22')
personal_distress <- c('6','10','13','17', '19', '24','27')
#compute scores
iri <- iri %>% mutate(PerspectiveTakingScore = rowSums(select(., perspective_taking), na.rm = TRUE),
                     FantasyScore = rowSums(select(., fantasy), na.rm = TRUE),
                     EmpathicConcernScore = rowSums(select(., empathic_concern), na.rm = TRUE),
                     PersonalDistressScore = rowSums(select(., personal_distress), na.rm = TRUE))
iri <- filter(iri, subID %in% dataSubs, subID != 20)

# make dataframes for comparison
emotion_rating_compare <- pivot_wider(emotion_rating, names_from = emotion, values_from = emoresp)
em_compare <- left_join(data_old, emotion_rating_compare, by = c('subID', 'vigfile', 'category'))
empathy_scores <- select(iri, PersonalDistressScore, EmpathicConcernScore, PerspectiveTakingScore, FantasyScore, subID)
em_compare <- left_join(em_compare, empathy_scores, by='subID') %>%
  drop_na(c(angry, sad, disgusted, afraid, contemptuous, amused, PersonalDistressScore, EmpathicConcernScore, PerspectiveTakingScore, FantasyScore))

# write tables with means 
# em_compare_means <- em_compare %>% group_by(category) %>% 
#   summarise(moral_judgment_mean = round(mean(moral_decision, na.rm = T), 3),
#             moral_judgment_SD = round(sd(moral_decision, na.rm = T), 3),
#             memory_accuracy_mean = round(mean(correct), 3),
#             memory_accuracy_SD = round(sd(correct), 3),
#             memory_confidence_mean = round(mean(confresp), 3),
#             memory_confidence_SD = round(sd(confresp), 3),
#             anger_mean = round(mean(angry, na.rm=T), 3),
#             anger_SD = round(sd(angry, na.rm = T), 3),
#             amusement_mean = round(mean(amused, na.rm=T), 3),
#             amusement_SD = round(sd(amused, na.rm=T), 3),
#             sadness_mean = round(mean(sad, na.rm=T), 3),
#             sadness_SD = round(sd(sad, na.rm=T), 3),
#             fear_mean = round(mean(afraid, na.rm=T), 3),
#             fear_SD = round(sd(afraid, na.rm=T), 3),
#             contempt_mean = round(mean(contemptuous, na.rm=T), 3),
#             contempt_SD = round(sd(contemptuous, na.rm = T), 3),
#             disgust_mean = round(mean(disgusted, na.rm=T), 3),
#             disgust_SD = round(sd(disgusted, na.rm=T),3),
#             personal_distress_mean = round(mean(PersonalDistressScore, na.rm=TRUE), 3),
#             personal_distress_SD = round(sd(PersonalDistressScore, na.rm=TRUE), 3),
#             empathic_concern_mean = round(mean(EmpathicConcernScore, na.rm=TRUE), 3),
#             empathic_concern_SD = round(sd(EmpathicConcernScore, na.rm=TRUE), 3),
#             perspective_taking_mean = round(mean(PerspectiveTakingScore, na.rm=TRUE), 3),
#             perspective_taking_SD = round(sd(PerspectiveTakingScore, na.rm=TRUE), 3),
#             fantasy_mean = round(mean(FantasyScore, na.rm=T), 3),
#             fantasy_SD = round(sd(FantasyScore, na.rm=T), 3))
# write.csv(em_compare_means, file = 'figures/paper/table_em_compareMeans.csv', row.names = F)

# scale em values for model fitting
em_compare <- em_compare %>% 
  mutate(angry = scale(angry),
         sad = scale(sad),
         disgusted = scale(disgusted),
         afraid = scale(afraid),
         contemptuous = scale(contemptuous),
         amused = scale(amused),
         PersonalDistressScore = scale(PersonalDistressScore),
         EmpathicConcernScore = scale(EmpathicConcernScore),
         PerspectiveTakingScore = scale(PerspectiveTakingScore),
         FantasyScore = scale(FantasyScore)) %>%
  filter(subID != '20')

# visualize variable correlations
# emotion_scores <- na.omit(em_compare[,20:27])
# corr <- cor(emotion_scores)
# ggcorrplot(corr, lab = TRUE)
# ggsave('emo_corr_matrix.png')

```

## Results: Moral Judgments
### Behavior
```{r Moral judgments: Behavior, message=FALSE, warning=FALSE, include=FALSE}

# # look at spread of moral judgement
# ggplot(data_old, aes(x=moral_decision, color=category, fill=category)) +
#   geom_bar() + 
#   facet_wrap(~category, nrow=2) + 
#   ggtitle('Distribution of Moral Judgments') +
#   xlab('1=not morally wrong, 4=extremely morally wrong')
# 
# compare our data to normed data from Clifford et al (2015)
mfv <- read.csv('data/mfv_norms.csv')
mfv$moral_decision <- scale(mfv$moral_decision)
mfv$dataset <- 'Normed'
mfv$category <- factor(mfv$category, levels = c('Social Norms', 'Authority', 'Loyalty', 'Sanctity',
                                                 'Harm-Phys', 'Harm-Emo', 'Fairness', 'Liberty'),
                       labels = c('Social Norms', 'Authority', 'Loyalty', 'Purity',
                                                 'Harm-Phys', 'Harm-Emo', 'Fairness', 'Liberty'))
mfv_comp <- data_old %>% select(category, vigfile, vignette, subID, moral_decision) %>%
  mutate(moral_decision = scale(moral_decision)) %>%
  group_by(vigfile) %>%
  summarise(moral_decision = mean(moral_decision)) %>%
  mutate(category = assignCategory(vigfile)) %>% 
  rename(vigtext = vigfile)
mfv_comp$dataset <- 'Ours'
mfv_comp <- rbind(mfv_comp, mfv)
mfv_comp$category <- factor(mfv_comp$category, levels = plotting_categories)

normCheck <- lm(moral_decision ~ dataset*category, data = mfv_comp)
summary(normCheck)

as.data.frame(emmeans(normCheck, ~ dataset*category)) %>%
  ggplot(aes(x = category, y = emmean, color = dataset, fill = dataset)) +
  geom_pointrange(aes(ymin = lower.CL, ymax = upper.CL), position = position_dodge(0.5)) +
  labs(y = 'Estimated mean moral judgment (scaled)', title = 'Comparison to Clifford et al. (2015)') +
  theme_pubr(base_family = 'Times New Roman', legend = 'right') +
  theme(axis.title.x = element_blank(),
        plot.title = element_text(hjust = 0.5))

# linear mixed effect model
modelMoral <- lmer(moral_decision ~ category + (1 | subID) + (1|vigfile), data = data_old, control=lmerControl(optCtrl = list(maxeval=5000))) 

tab_model(modelMoral, 
          #file = 'figures/paper/table_modelMoral.html',  
          digits = 3, 
          show.ci = 0.95, show.stat = TRUE, show.p = TRUE, show.ngroups = TRUE, show.df = TRUE,
          p.val = 'satterthwaite', 
          strings = c(stat = 't value', ci = 'CI (95%)', pred = 'Factors', p = 'p value'),
          dv.labels = 'moral judgment', 
          col.order = c('est','ci','df.error','stat','p'),
          pred.labels = c('Intercept (Social Norms)', 
                          'Authority', 'Loyalty', 'Purity', 'Harm-Emo', 'Harm-Phys', 'Fairness', 'Liberty'),
          title = 'Table 1: Moral judgment model summary')

# effect size
emmeans(modelMoral, ~ category) %>% 
  eff_size(sigma=sd(data_old$moral_decision), edf=df.residual(modelMoral), method='trt.vs.ctrl')

# contrasts
supContrastMoral <- modelMoral %>% 
  emmeans(~ category) %>%
  contrast(SuperordinateContrasts, adjust = 'tukey')
supContrastMoral.eff <- eff_size(supContrastMoral, sigma = sd(data_old$moral_decision), edf = df.residual(modelMoral), method = 'identity') %>%
  as.data.frame() %>%
  mutate(effect.size = round(effect.size, 2))
supContrastMoral.df <- as.data.frame(supContrastMoral) %>%
  mutate_at(c('estimate', 'SE', 'df', 't.ratio'), funs(round(.,2)))
supContrastMoral.df$eff_size <- supContrastMoral.eff$effect.size 
write.csv(supContrastMoral.df, file = 'figures/paper/table_supContrastMoral.csv', row.names = F)

supContrastMoralNew <- modelMoral %>% 
  emmeans(~ category) %>%
  contrast(newSuperordinateContrasts, adjust = 'tukey')
supContrastMoralNew.eff <- eff_size(supContrastMoralNew, sigma = sd(data_old$moral_decision), edf = df.residual(modelMoral), method = 'identity') %>%
  as.data.frame() %>%
  mutate(effect.size = round(effect.size, 2))
supContrastMoralNew.df <- as.data.frame(supContrastMoralNew) %>%
  mutate_at(c('estimate', 'SE', 'df', 't.ratio'), funs(round(.,2)))
supContrastMoralNew.df$eff_size <- supContrastMoralNew.eff$effect.size 
write.csv(supContrastMoralNew.df, file = 'figures/paper/table_supContrastMoralNew.csv', row.names = F)


# plot
modelMoral_df <- as.data.frame(emmeans(modelMoral, ~ category))
ggplot(modelMoral_df, aes(x=category, y=emmean)) +
  ylim(0.98,4) +
  labs(x = 'Foundation', y='Estimated marginal mean', fill='Foundation') +
  geom_violin(data=data_old, mapping=aes(y=moral_decision, fill=category), alpha=0.85, bw=0.45) + 
  geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL), alpha=1, fatten=5, color='black') +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'none',
             base_family = 'Times New Roman',
             base_size = 20) +
  theme(axis.title.x = element_blank())
ggsave('figures/paper/plot_modelMoral.png', dpi=300)
```


### Task PLS results: LV1 
```{r make LV plots, include=FALSE}
p1 <- ggplot(data = mean_centered_results_LV1, 
       aes(x=category, y=LV1, fill=category, color=category)) +
  geom_hline(aes(yintercept = 0), size = 0.5) +
  labs(y = 'Brain scores', x = 'Foundation', title = 'LV1: 24.4% crossblock variance') +
  geom_col(color='black') + 
  geom_point(color='black', size=1) +
  geom_errorbar(aes(ymax = upper, ymin = lower), color='black', size=0.5, width=0.25) +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'none') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14))

modelLV1 <- lmer(score ~ lag * category + (1 | subID), data = LV1)
p2 <- modelLV1 %>% emmeans(~ lag * category) %>% as.data.frame() %>%
  mutate(superordinate = superordinateCategory(category),
         category = factor(category, levels = plotting_categories)) %>%
  ggplot(aes(x=lag, y=emmean, group=category, color=category, fill=category))  + 
  scale_x_discrete(expand = c(0, 0, 0, 0.08), labels = c('TR1', 'TR2', 'TR3', 'TR4')) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'right') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14)) +
  labs(y = 'Brain score', x= 'TR=2s', color='Foundation', fill='Foundation', shape='Foundation') +
  ggtitle('Temporal brain scores')
ggsave('../4TR_LV1.png', width = 8)


p3 <- ggplot(data = mean_centered_results_LV2, 
       aes(x=category, y=LV2, fill=category, color=category)) +
  geom_hline(aes(yintercept = 0), size = 0.5) +
  labs(y = 'Brain scores', tag = 'D.') +
  geom_col(color='black') + 
  geom_point(color='black', size=1) +
  geom_errorbar(aes(ymax = upper, ymin = lower), color='black', size=0.5, width=0.25) +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'none') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=14),
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14)) +
  ggtitle('LV2: 18.13% crossblock variance')

ggplot(data = mean_centered_results_LV2, 
       aes(x=category, y=LV2, fill=category, color=category)) +
  geom_hline(aes(yintercept = 0), size = 0.5) +
labs(y = 'Brain scores', x = 'Foundation', title = 'LV2: 18.13% crossblock variance') +
  geom_col(color='black') + 
  geom_point(color='black', size=1) +
  geom_errorbar(aes(ymax = upper, ymin = lower), color='black', size=0.5, width=0.1) +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'none', base_family = 'Avenir') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=16),
        axis.text = element_text(size = 16),
        plot.title = element_text(hjust = 0.5, size = 20, face = 'bold'))
ggsave('../poster/LV2_pattern.png', width = 10)

modelLV2 <- lmer(score ~ lag * category + (1 | subID), data = LV2)

p4 <- modelLV2 %>% emmeans(~ lag * category) %>% as.data.frame() %>%
  mutate(superordinate = superordinateCategory(category),
         category = factor(category, levels = plotting_categories)) %>%
  ggplot(aes(x=lag, y=emmean, group=category, color=category, fill=category))  + 
  scale_x_discrete(expand = c(0, 0, 0, 0.08), labels = c('TR1', 'TR2', 'TR3', 'TR4')) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  MFT_fill() + MFT_color() +
  theme_pubr(legend = 'right') +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(), 
        axis.text = element_text(size = 12),
        plot.title = element_text(hjust = 0.5, size = 14)) +
  labs(x= 'TR=2s', color='Foundation', fill='Foundation', shape='Foundation', tag = 'E.', title = 'Temporal brain scores')


p1 + p2 +  
  plot_layout(widths = c(2, 1)) +
  plot_layout(guides = 'collect') + 
  plot_annotation(tag_levels = 'A', tag_suffix = '.') & 
  theme(text = element_text(family = 'Times New Roman'), plot.tag = element_text(size = 11))
ggsave('figures/paper/plot_LV1.png', width = 15, height = 4.5, dpi = 'retina')

p3 + p4 +
  plot_layout(widths = c(2, 1.45)) +
  plot_layout(guides = 'collect') & 
  theme(text = element_text(family = 'Times New Roman'), plot.tag = element_text(size = 11))
ggsave('figures/paper/plot_LV2.png', width = 15, height = 4.5, dpi = 'retina')


## Non-rotated PLS - not including these plots in the paper ##
# Analysis 1: individualizing vs. binding
# ggplot(data = nr_superordinate, 
#        aes(x=category, y=V1, color=category, fill=category)) +
#   geom_hline(aes(yintercept = 0), size = 0.5) +
#   labs(y='Brain scores', x='Foundation') +
#   geom_col(color='black') + 
#   geom_point(color='black', size=1) +
#   geom_errorbar(aes(ymax = upper, ymin = lower), color='black', size=0.5, width=0.25) +
#   MFT_fill() +
#   theme_pubr(legend = 'none') +
#   theme(axis.title = element_text(size = 12),
#         axis.text = element_text(size=10),
#         title = element_text(size=12),
#         plot.title = element_text(hjust = 0.5, face = 'bold')) +
#   ggtitle('Individualizing vs. Binding: p < 0.519')
# 
# # Social Norms vs. everything else 
# ggplot(data = nr_social, 
#        aes(x=category, y=V1, color=category, fill=category)) +
#   geom_hline(aes(yintercept = 0), size = 0.5) +
#   labs(y='Brain scores', x='Foundation') +
#   geom_col(color='black') + 
#   geom_point(color='black', size=1) +
#   geom_errorbar(aes(ymax = upper, ymin = lower), color='black', size=0.5, width=0.25) +
#   MFT_fill() + 
#   theme_pubr(legend = 'none') +
#   theme(axis.title.x = element_text(size = 12),
#         axis.title.y = element_blank(),
#         axis.text = element_text(size=10),
#         title = element_text(size=12),
#         plot.title = element_text(hjust = 0.5, face = 'bold')) +
#   ggtitle('Social Norms vs. Moral Foundations: p < 0.059')
```

# Model comparisons
### different superordinate categories 
```{r superordinate model comparisons}
superordinateNull <- lmer(moral_decision ~ 1 + (1|subID) + (1|vigfile), data = data_old, control=lmerControl(optCtrl = list(maxeval=5000))) 
superordinateOG <- lmer(moral_decision ~ superordinate + (1|subID) + (1|vigfile), data = data_old, control=lmerControl(optCtrl = list(maxeval=5000))) 
superordinateNew <- lmer(moral_decision ~ superordinate_new + (1|subID) + (1|vigfile), data = data_old, control=lmerControl(optCtrl = list(maxeval=5000))) 

supCompMoral.df <- compare_performance(superordinateNull, modelMoral, superordinateOG, superordinateNew, 
                                       bayesfactor = FALSE, rank = TRUE) %>% 
  as.data.frame() %>% 
  mutate(AIC = round(AIC, 2),
         BIC = round(BIC, 2),
         R2_conditional = round(R2_conditional, 2),
         R2_marginal = round(R2_marginal, 2),
         ICC = round(ICC, 2),
         RMSE = round(RMSE, 2))
write.csv(supCompMoral.df, file = 'figures/paper/table_supCompMoral.csv', row.names = F)
```

### empathy & emotion model comparison
```{r em model comparison}
# baseline: no fixed effects
em_null_moral <- lmer(moral_decision ~ 1 + (1|subID) + (1|vigfile), data = em_compare) 

# standard: category as fixed effect
em_modelMoral <- lmer(moral_decision ~ category + (1|subID) + (1|vigfile), data = em_compare, contrasts = list(category=contr.sum))

# just emotion & empathy as fixed effects
em_only_moral <- lmer(moral_decision ~ angry + sad + disgusted + afraid + contemptuous + amused +
                       PersonalDistressScore + EmpathicConcernScore + PerspectiveTakingScore + FantasyScore +
                        (1|subID) + (1|vigfile), data=em_compare)

# add emotion & empathy to foundations
em_add_moral <- lmer(moral_decision ~ category + angry + sad + disgusted + afraid + contemptuous + amused +
                       PersonalDistressScore + EmpathicConcernScore + PerspectiveTakingScore + FantasyScore +
                        (1|subID) + (1|vigfile), data=em_compare, contrasts = list(category=contr.sum))

# each em (emotion & empathy) measure interacts with category
em_int_moral <- lmer(moral_decision ~ 
                        category * angry + 
                        category * sad + 
                        category * disgusted + 
                        category * afraid + 
                        category * contemptuous + 
                        category * amused + 
                        category * PersonalDistressScore + 
                        category * EmpathicConcernScore + 
                        category * PerspectiveTakingScore +
                        category * FantasyScore +
                        (1|subID) + (1|vigfile), data = em_compare,
                    contrasts = list(category=contr.sum))

em_comp_moral.df <- compare_performance(em_null_moral, em_modelMoral, em_only_moral, em_add_moral, em_int_moral,
                                        bayesfactor = FALSE, rank = TRUE) %>% 
  as.data.frame() %>% 
  mutate(AIC = round(AIC, 2),
         BIC = round(BIC, 2),
         R2_conditional = round(R2_conditional, 2),
         R2_marginal = round(R2_marginal, 2),
         ICC = round(ICC, 2),
         RMSE = round(RMSE, 2))
write.csv(em_comp_moral.df, file = 'figures/paper/table_emCompMoral.csv', row.names = F)
```

```{r sum-code em_category, include = FALSE}
# make pretty table
tab_model(em_add_moral,
          file = 'figures/paper/table_Emotion+Empathy+Foundation.html',
          digits = 2, 
          show.ci = 0.95, show.stat = TRUE, show.p = TRUE, show.ngroups = TRUE, show.df = TRUE,
          p.val = 'satterthwaite', 
          strings = c(stat = 't value', ci = 'CI (95%)', pred = 'Factors', p = 'p value'),
          dv.labels = 'moral judgment', 
          col.order = c('est','ci','df.error','stat','p'),
          pred.labels = c('Intercept',
                          'Social Norms', 'Authority', 'Loyalty', 'Purity', 'Harm-Emo', 'Harm-Phys', 'Fairness', 
                          'Anger', 'Sadness', 'Disgust', 'Fear','Contempt','Amusement', 
                          'Personal Distress Score', 'Empathic Concern Score', 'Perspective Taking Score', 'Fantasy Score'))

# compute effect size
emmeans(em_add_moral, ~ category) %>% 
  eff_size(sigma=sd(em_compare$moral_decision), edf=df.residual(em_add_moral), method='eff')

em_add.cov <- list(angry=0, amused=0, sad=0, afraid=0, contemptuous=0, disgusted=0,
                        PersonalDistressScore=0, EmpathicConcernScore=0,
                        PerspectiveTakingScore=0, FantasyScore=0)

em_add_effsize <- function(model, dv, em_measure) {
   arglist <- list(em_add.cov, c(0,1))
   names(arglist) <- c('.x', em_measure)
   return(emmeans(model, as.formula(paste0('~', em_measure)),
                  at=do.call(list_modify, arglist)) %>%
     eff_size(sigma=sd(em_compare[,c(dv)]), edf=df.residual(model), method='revpairwise'))
}

em_add_effsize(em_add_moral, 'moral_decision', 'angry')
em_add_effsize(em_add_moral, 'moral_decision', 'sad')
em_add_effsize(em_add_moral, 'moral_decision', 'disgusted')
em_add_effsize(em_add_moral, 'moral_decision', 'afraid')
em_add_effsize(em_add_moral, 'moral_decision', 'contemptuous')
em_add_effsize(em_add_moral, 'moral_decision', 'amused')
em_add_effsize(em_add_moral, 'moral_decision', 'PersonalDistressScore')
em_add_effsize(em_add_moral, 'moral_decision', 'EmpathicConcernScore')
em_add_effsize(em_add_moral, 'moral_decision', 'PerspectiveTakingScore')
em_add_effsize(em_add_moral, 'moral_decision', 'FantasyScore')
```

## Memory
### Accuracy (hits & correct rejections)
```{r, fig.width=20, fig.height=8, include=FALSE}

# generalized linear mixed effect model (outcome is binary)
modelMemory <- glmer(correct ~ category * old + (1|subID) + (1|vigfile),
                     data=data, family = binomial(link = 'logit'), 
                     control=glmerControl(optimizer = 'bobyqa', optCtrl = list(maxfun=5000)),
                     contrasts = list(category=contr.sum))
summary(modelMemory)
exp(fixef(modelMemory))

# make pretty table
tab_model(modelMemory, 
          file = 'figures/paper/table_modelMemory.html',  
          digits = 3, 
          show.ci = 0.95, show.stat = TRUE, show.p = TRUE, show.ngroups = TRUE, show.df = TRUE,
          #p.val = 'satterthwaite', 
          strings = c(stat = 'z value', ci = 'CI (95%)', pred = 'Factors', p = 'p value'),
          dv.labels = 'correct', 
          col.order = c('est','ci','df.error','stat','p'),
          pred.labels = c('Intercept', 
                          'Social Norms', 'Authority', 'Loyalty', 'Purity', 'Harm-Emo', 'Harm-Phys', 'Fairness',
                          'New - Old', 'Social Norms*New', 'Authority*New', 'Loyalty*New', 'Purity*New', 'Harm-Emo*New', 'Harm-Phys*New',
                          'Fairness*New'))

# compute effect size 
emmeans(modelMemory, ~ category, at=list(c(old=1)), type = 'response') %>%
  eff_size(sigma = sd(data$correct), edf = df.residual(modelMemory), method = 'eff')

emmeans(modelMemory, ~ old, type = 'response') %>%
  eff_size(sigma = sd(data$correct), edf = df.residual(modelMemory), method = 'eff')

emmeans(modelMemory, ~ old | category, at=list(c(old=0,1)), type='response') %>% 
  contrast(interaction=c('revpairwise', 'eff')) %>%
  eff_size(sigma = sd(data$correct), edf = df.residual(modelMemory), method = 'identity')

# plotting prep
data <- data %>% group_by(subID, category, old) %>% mutate(propCorrect = mean(correct)) # so that violin plots can reflect participant response densities
memLabels <- c('0' = "New", '1' = 'Old') # labels for faceting 
data$superordinate_new <- superordinateNew(data$category)

# plot
emmeans(modelMemory, ~ category*old, type = 'response') %>% as.data.frame %>%
  ggplot(aes(x=category, y=prob, fill=interaction(category,old))) +
  geom_violin(aes(x=category, y=propCorrect), data=data, alpha=0.85, scale='count', bw=.1) +
  geom_pointrange(aes(y=prob, ymax=asymp.LCL, ymin=asymp.UCL, shape=old), 
                  position = position_dodge(0.9), color='black', fatten=4) +
  scale_shape_manual(values = c(16,21), labels = c('Old', 'New')) +
  MFT_memfill() +
  theme_pubr(legend = 'right',
             base_family = 'Times New Roman',
             base_size = 15) +
  guides(fill=FALSE, shape=guide_legend(title=NULL)) +
  theme(plot.title = element_text(hjust = 0.5),
        legend.text = element_text(size = 18),
        axis.title.x = element_blank()) + 
  labs(x = 'Foundation', y = 'Estimate probability of correct response', color = 'Old/New Status')

ggsave('figures/paper/plot_modelMemory.png')

# superordinate model comparison
modelMemoryNull <- glmer(correct ~ old + (1 | subID) + (1|vigfile),
                 data=data, family=binomial(link = 'logit'),
                 control=glmerControl(optimizer = 'bobyqa', optCtrl=list(maxfun=5000)),
                 contrasts = list(category=contr.sum))

modelSupMemory <- glmer(correct ~ superordinate * old + (1 | subID) + (1|vigfile),
                 data=data, family=binomial(link = 'logit'), 
                 control=glmerControl(optimizer = 'bobyqa', optCtrl=list(maxfun=5000)),
                 contrasts = list(superordinate=contr.sum))

modelSupMemoryNew <- glmer(correct ~ superordinate_new * old + (1 | subID) + (1|vigfile),
                 data=data, family=binomial(link = 'logit'), 
                 control=glmerControl(optimizer = 'bobyqa',optCtrl=list(maxfun=5000)),
                 contrasts = list(superordinate_new=contr.sum))

compare_performance(modelMemoryNull, modelSupMemory, modelSupMemoryNew, modelMemory, bayesfactor = FALSE, rank = TRUE)

# superordinate contrasts 
supContrastMemory.df <- emmeans(modelMemory, ~ old * category, type = 'response', lmer.df = 'satterthwaite') %>% 
  contrast(interaction = c("pairwise", old_superordinate, by = NULL)) %>% as.data.frame() %>%
  mutate(odds_ratio = round(exp(estimate),2),
         estimate = round(estimate, 2),
         SE = round(SE, 2),
         z.ratio = round(z.ratio, 2),
         p.value = round(p.value, 3)) 
write.csv(supContrastMemory.df, file = 'figures/paper/table_supContrastMemory.csv', row.names = F)

supContrastMemoryNew.df <- emmeans(modelMemory, ~ old * category, type = 'response', lmer.df = 'satterthwaite') %>% 
  contrast(interaction = c("pairwise", new_superordinate, by = NULL)) %>% as.data.frame() %>%
  mutate(odds_ratio = round(exp(estimate),2),
         estimate = round(estimate, 2),
         SE = round(SE, 2),
         z.ratio = round(z.ratio, 2),
         p.value = round(p.value, 3))
write.csv(supContrastMemoryNew.df, file = 'figures/paper/table_supContrastMemoryNew.csv', row.names = F)

# em model comparison
em_null_memory <- glmer(correct ~ 1 + (1 | subID) + (1|vigfile),
                 data=em_compare, family=binomial(link = 'logit'), control=glmerControl(optCtrl=list(maxfun=50000)))

em_modelMemory <- glmer(correct ~ category + (1|subID) + (1|vigfile),
                     data=em_compare, family = binomial(link = 'logit'), control=glmerControl(optCtrl = list(maxfun=5000),
                                                                                              optimizer = 'bobyqa'))

em_only_memory <- glmer(correct ~ angry + sad + disgusted + afraid + contemptuous + amused +
                       PersonalDistressScore + EmpathicConcernScore +
                       (1|subID) + (1|vigfile),
                       data=em_compare, family = binomial(link = 'logit'), control=glmerControl(optCtrl = list(maxfun=5000),
                                                                                                optimizer = 'bobyqa'))

em_add_memory <- glmer(correct ~ category + angry + sad + disgusted + afraid + contemptuous + amused +
                       PersonalDistressScore + EmpathicConcernScore +
                       (1|subID) + (1|vigfile),
                       data=em_compare, family = binomial(link = 'logit'), control=glmerControl(optCtrl = list(maxfun=5000),
                                                                                                optimizer = 'bobyqa'))

em_int_memory <- glmer(correct ~ 
                                 category * angry + 
                                 category * amused + 
                                 category * sad + 
                                 category * afraid + 
                                 category * contemptuous + 
                                 category * disgusted + 
                                 category * PersonalDistressScore + 
                                 category * EmpathicConcernScore + 
                                 (1 | subID) + (1|vigfile),
                 data=em_compare, family=binomial(link = 'logit'), control=glmerControl(optCtrl=list(maxfun=1e9),
                                                                                        optimizer = 'bobyqa'))

emCompMemory.df <- compare_performance(em_null_memory, em_modelMemory, em_only_memory, em_add_memory, em_int_memory, 
                    bayesfactor = FALSE, rank = TRUE, metrics = c('AIC', 'BIC', 'R2', 'ICC', 'RMSE')) %>% 
  as.data.frame() %>% 
  mutate(AIC = round(AIC, 2),
         BIC = round(BIC, 2),
         R2_conditional = round(R2_conditional, 2),
         R2_marginal = round(R2_marginal, 2),
         ICC = round(ICC, 2),
         RMSE = round(RMSE, 2))
write.csv(emCompMemory.df, file = 'figures/paper/table_emCompMemory.csv', row.names = FALSE)
```

### Confidence
```{r, fig.width=8, fig.height=4, include=FALSE}
data$correct <- factor(data$correct, levels = c('1','0'))

# run model
modelConfidence <- lmer(confresp ~ category * old * correct + (1 | subID) + (1|vigfile), data=data,
                        control=lmerControl(optCtrl = list(maxeval=5000)),
                        contrasts = list(category=contr.sum))
tab_model(modelConfidence, 
          #file = 'figures/paper/table_modelConfidence.html',  
          digits = 2, 
          show.ci = 0.95, show.stat = TRUE, show.p = TRUE, show.ngroups = TRUE, show.df = TRUE,
          p.val = 'satterthwaite', 
          strings = c(stat = 't value', ci = 'CI (95%)', pred = 'Factors', p = 'p value'),
          dv.labels = 'confidence', 
          col.order = c('est','ci','df.error','stat','p'),
          pred.labels = c('Intercept', 
                          'Social Norms', 'Authority', 'Loyalty', 'Purity', 'Harm-Emo', 'Harm-Phys', 'Fairness',
                          'New', 'Incorrect',
                          'Social Norms*New', 'Authority*New', 'Loyalty*New', 'Purity*New', 'Harm-Emo*New', 'Harm-Phys*New','Fairness*New',
                          'Social Norms*Incorrect', 'Authority*Incorrect', 'Loyalty*Incorrect', 'Purity*Incorrect', 
                          'Harm-Emo*Incorrect', 'Harm-Phys*Incorrect','Fairness*Incorrect',
                          'New*Incorrect',
                          'Social Norms*New*Incorrect', 'Authority*New*Incorrect', 'Loyalty*New*Incorrect', 'Purity*New*Incorrect', 
                          'Harm-Emo*New*Incorrect', 'Harm-Phys*New*Incorrect','Fairness*New*Incorrect'))

# plot
modelConfidence_df <- modelConfidence %>% emmeans(~ category * old * correct, type='response') %>% as.data.frame

ggplot(modelConfidence_df, aes(x=category, y=emmean)) +
  facet_wrap(. ~ correct, labeller = (correct=as_labeller(confLabels))) +
  geom_pointrange(aes(ymax=upper.CL, ymin=lower.CL, shape=old, color=category), size = 0.85, position=position_dodge(0.5)) + 
  scale_shape_manual(values = c(16,1), labels = c('Old', 'New')) +
  ylim(0,4) +
  MFT_color() + MFT_fill() + 
  theme_pubr(legend = 'top',
             base_family = 'Times New Roman') +
  guides(color=FALSE, shape=guide_legend(title=NULL)) +
  theme(strip.text.x = element_text(size=16, face='bold'), 
        strip.background = element_rect(color = 'white'),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=12),
        legend.text = element_text(size=14),
        legend.position = c(0.05, 0.89)) +
  labs(y = 'Estimated mean confidence', x = 'Foundation', color = 'Foundation')
ggsave('figures/paper/plot_modelConfidence.png', dpi = 'retina', width = 14, height = 4)

# superordinate model comparison
modelConfidenceNull <- lmer(confresp ~  old * correct + (1 | subID) + (1|vigfile), data=data,
                        control=lmerControl(optCtrl = list(maxeval=5000)))
modelConfidenceSup <- lmer(confresp ~ superordinate * old * correct + (1 | subID) + (1|vigfile), 
                           data=data,control=lmerControl(optCtrl = list(maxeval=5000)))
modelConfidenceSupNew <- lmer(confresp ~ superordinate_new * old * correct + (1 | subID) + (1|vigfile), 
                              data=data,control=lmerControl(optCtrl = list(maxeval=5000)))

supCompConf.df <- as.data.frame(compare_performance(modelConfidenceNull, modelConfidenceSup, modelConfidenceSupNew, modelConfidence, bayesfactor = F)) %>% 
  mutate_at(c('AIC', 'BIC', 'R2_conditional', 'R2_marginal', 'ICC', 'RMSE'), funs(round(., 2)))
write.csv(supCompConf.df, file = 'figures/paper/table_supCompConf.csv', row.names = F)

# superordinate contrasts
supContrastConf <- modelConfidence %>% 
  emmeans(~ old * correct * category, type = 'response') %>%
  contrast(interaction=c('pairwise', 'pairwise', old_superordinate))
supContrastConf.eff <- eff_size(supContrastConf, sigma = sd(data$confresp), edf = df.residual(modelConfidence), method = 'identity') %>% as.data.frame() %>% mutate(effect.size = round(effect.size, 2))
supContrastConf.df <- as.data.frame(supContrastConf) %>%
  mutate_at(c('estimate', 'SE', 'df', 't.ratio'), funs(round(.,2)))
supContrastConf.df$eff_size <- supContrastConf.eff$effect.size 
write.csv(supContrastConf.df, file = 'figures/paper/table_supContrastConf.csv', row.names = F)

supContrastConfNew <- modelConfidence %>% 
  emmeans(~ old * correct * category, type = 'response') %>%
    contrast(interaction=c('pairwise', 'pairwise', new_superordinate))
supContrastConfNew.eff <- eff_size(supContrastConfNew, sigma = sd(data$confresp), edf = df.residual(modelConfidence), method = 'identity') %>%
  as.data.frame() %>% mutate(effect.size = round(effect.size, 2))
supContrastConfNew.df <- as.data.frame(supContrastConfNew) %>%
  mutate_at(c('estimate', 'SE', 'df', 't.ratio'), funs(round(.,2)))
supContrastConfNew.df$eff_size <- supContrastConfNew.eff$effect.size 
write.csv(supContrastConfNew.df, file = 'figures/paper/table_supContrastConfNew.csv', row.names = F)

# em model comparisons
em_null_confidence <- lmer(confresp ~  correct + (1 | subID) + (1|vigfile), 
                            data=em_compare, control=lmerControl(optCtrl = list(maxeval=5000)))

em_modelConfidence <- lmer(confresp ~ category * correct + (1 | subID) + (1|vigfile), 
                        data=em_compare, control=lmerControl(optCtrl = list(maxeval=5000)))

em_only_confidence <- lmer(confresp ~ correct + angry + sad + disgusted + afraid + contemptuous + amused +
                             PersonalDistressScore + EmpathicConcernScore + PerspectiveTakingScore + FantasyScore +
                             (1 | subID) + (1|vigfile), 
                        data=em_compare, control=lmerControl(optCtrl = list(maxeval=5000)))

em_add_confidence <- lmer(confresp ~ category + correct +  angry + sad + disgusted + afraid + contemptuous + amused +
                             PersonalDistressScore + EmpathicConcernScore + PerspectiveTakingScore + FantasyScore +
                        (1|subID) + (1|vigfile),
                        data=em_compare, control=lmerControl(optCtrl = list(maxeval=5000)))

em_int_confidence1 <- lmer(confresp ~ correct +
                                 category * angry + 
                                 category * amused + 
                                 category * sad + 
                                 category * afraid + 
                                 category * contemptuous + 
                                 category * disgusted + 
                                 category * PersonalDistressScore + 
                                 category * EmpathicConcernScore + 
                                 (1 | subID) + (1|vigfile),
                 data=em_compare, control=lmerControl(optCtrl=list(maxfun=5000)))

em_int_confidence2 <- lmer(confresp ~ 
                                 correct * category * angry + 
                                 correct * category * amused + 
                                 correct * category * sad + 
                                 correct * category * afraid + 
                                 correct * category * contemptuous + 
                                 correct * category * disgusted + 
                                 correct * category * PersonalDistressScore + 
                                 correct * category * EmpathicConcernScore + 
                                 (1 | subID) + (1|vigfile),
                 data=em_compare, control=lmerControl(optCtrl=list(maxfun=5000)))

emCompConf.df <- compare_performance(em_null_confidence, em_modelConfidence, em_only_confidence, em_add_confidence, em_int_confidence1, em_int_confidence2, bayesfactor = FALSE, rank = TRUE) %>% 
  as.data.frame() %>%
  mutate(AIC = round(AIC, 2),
         BIC = round(BIC,2),
         R2_marginal = round(R2_marginal, 2),
         R2_conditional = round(R2_conditional, 2),
         ICC = round(ICC, 2),
         RMSE = round(RMSE, 2))
write.csv(emCompConf.df, file = 'figures/paper/table_emCompConf.csv', row.names = F)
```

# multiple voxel extraction
```{r}
assignSupLV1 <- function(c) {
  return(ifelse(c == 'Authority', 0,
         ifelse(c == 'Harm-Emo', 1,
         ifelse(c == 'Harm-Phys', 1,
         ifelse(c == 'Purity', 1,
         ifelse(c == 'Fairness', 0,
         ifelse(c == 'Loyalty', 0,
         ifelse(c == 'Liberty', 0,
         ifelse(c == 'Social Norms', 0, NA)))))))))
}
# amygdala
amyg_activity1 <- read.delim(file = '../MFT_PLS/4_TR_analysis/multiple voxel extraction/amygdala/amygdala1_fMRIvoxeldata.txt', header = FALSE, sep = "")
colnames(amyg_activity1) <- c('TR1','TR2','TR3','TR4')
amyg_activity1$category <- rep(matlab_categories, each=27)
amyg_activity1$subID <- dataSubs
amyg_activity1 <- pivot_longer(amyg_activity1, cols = c(TR1, TR2, TR3, TR4), names_to = 'TR', values_to = 'Intensity')
amyg_activity1$category <- factor(amyg_activity1$category, levels = plotting_categories)
amyg_activity1_means <- amyg_activity1 %>% group_by(category, TR) %>%
  summarise(Intensity = mean(Intensity))
amyg_activity1_means$alpha <- assignSupLV1(amyg_activity1_means$category)

amy1 <- ggplot(amyg_activity1_means, aes(x=TR, y=Intensity, color=category, group = category, alpha = alpha == 0)) +
  scale_x_discrete(expand = c(0, 0, 0, 0.08)) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  scale_alpha_manual(values = c(1, 0.3), guide = FALSE) +
  MFT_color() + 
  theme_pubr(legend = 'right') +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle('(-32, -4, -20)')

amyg_activity2 <- read.delim(file = '../MFT_PLS/4_TR_analysis/multiple voxel extraction/amygdala/amygdala2_fMRIvoxeldata.txt', header = FALSE, sep = "")
colnames(amyg_activity2) <- c('TR1','TR2','TR3','TR4')
amyg_activity2$category <- rep(matlab_categories, each=27)
amyg_activity2$subID <- dataSubs
amyg_activity2 <- pivot_longer(amyg_activity2, cols = c(TR1, TR2, TR3, TR4), names_to = 'TR', values_to = 'Intensity')
amyg_activity2$category <- factor(amyg_activity2$category, levels = plotting_categories)
amyg_activity2_means <- amyg_activity2 %>% group_by(category, TR) %>%
  summarise(Intensity = mean(Intensity))
amyg_activity2_means$alpha <- assignSupLV1(amyg_activity2_means$category)

amy2 <- ggplot(amyg_activity2_means, aes(x=TR, y=Intensity, color=category, group = category, alpha = alpha == 0)) +
  scale_x_discrete(expand = c(0, 0, 0, 0.08)) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  scale_alpha_manual(values = c(1, 0.3), guide = FALSE) +
  MFT_color() + 
  theme_pubr(legend = 'right') +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle('(-18, -8, -14)')

amyg_activity3 <- read.delim(file = '../MFT_PLS/4_TR_analysis/multiple voxel extraction/amygdala/amygdala3_fMRIvoxeldata.txt', header = FALSE, sep = "")
colnames(amyg_activity3) <- c('TR1','TR2','TR3','TR4')
amyg_activity3$category <- rep(matlab_categories, each=27)
amyg_activity3$subID <- dataSubs
amyg_activity3 <- pivot_longer(amyg_activity3, cols = c(TR1, TR2, TR3, TR4), names_to = 'TR', values_to = 'Intensity')
amyg_activity3$category <- factor(amyg_activity3$category, levels = plotting_categories)
amyg_activity3_means <- amyg_activity3 %>% group_by(category, TR) %>%
  summarise(Intensity = mean(Intensity))
amyg_activity3_means$alpha <- assignSupLV1(amyg_activity3_means$category)


amy3 <- ggplot(amyg_activity3_means, aes(x=TR, y=Intensity, color=category, group = category, alpha = alpha == 0)) +
  scale_x_discrete(expand = c(0, 0, 0, 0.08)) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  scale_alpha_manual(values = c(1, 0.3), guide = FALSE) +
  MFT_color() + 
  theme_pubr(legend = 'right') +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle('(20, -8, -16)')

amy1 + amy2 + amy3 + plot_layout(guides = 'collect') 


insula_activity <- read.delim(file = '../MFT_PLS/4_TR_analysis/multiple voxel extraction/insula/insula_fMRIvoxeldata.txt', header = FALSE, sep = "")
colnames(insula_activity) <- c('TR1','TR2','TR3','TR4')
insula_activity$category <- rep(matlab_categories, each=27)
insula_activity$subID <- dataSubs
insula_activity <- pivot_longer(insula_activity, cols = c(TR1, TR2, TR3, TR4), names_to = 'TR', values_to = 'Intensity')
insula_activity$category <- factor(insula_activity$category, levels = plotting_categories)
insula_activity_means <- insula_activity %>% group_by(category, TR) %>%
  summarise(Intensity = mean(Intensity))

ggplot(insula_activity_means, aes(x=TR, y=Intensity, color=category, group = category)) +
  scale_x_discrete(expand = c(0, 0, 0, 0.08)) +
  geom_hline(aes(yintercept = 0), size=1) +
  geom_line(size=1) + 
  geom_point(aes(fill=category, color=category, shape = category), size=3) +
  scale_shape_manual(values = c(4,15,16,17,0,1,2, 3)) +
  MFT_color() + 
  theme_pubr() +
  ggtitle('Insula voxel response')

```

# Manuscript things
```{r summary tables and such}
# participant demographics -- this data is not available in the repo
# full_demographics <- read.csv('data/ppt_log.csv', stringsAsFactors = FALSE)
# sex_distribution <- full_demographics %>% 
#   filter(MFT_id %in% dataSubs) %>% 
#   count(Sex)
# age_stats <- full_demographics %>% 
#   filter(MFT_id %in% dataSubs) %>% 
#   mutate(Birthdate = as.Date(Birthdate), #as.Date is from eeptools, which is not compatible with R version 4.0.0
#          Scan.date = as.Date(Scan.date),
#          age = age_calc(Birthdate, Scan.date, units = 'years')) %>%
#   summarise(meanAge = mean(age), SD = sd(age))

# write table with means for supplement
data_means <- data %>% group_by(category, old) %>% summarise(moral_judgment_mean = round(mean(moral_decision, na.rm = T), 3),
                                                                 moral_judgment_SD = round(sd(moral_decision, na.rm = T), 3),
                                                                 memory_accuracy_mean = round(mean(correct), 3),
                                                                 memory_accuracy_SD = round(sd(correct), 3),
                                                                 memory_confidence_mean = round(mean(confresp), 3),
                                                                 memory_confidence_SD = round(sd(confresp), 3))
write.csv(data_means, file = 'figures/paper/table_dataMeans.csv', row.names = F)
```

### Old code -- not used
```{r, include=FALSE}
## some handy commands
# exp(fixef(modelOld1)): transforms model output from log likelihood to odds ratio
# anova(modelOld1, modelOld2): use for model comparisons [**don't look at the output of either model; use the results of this comparison to guide your result-seeking**]
# emmeans(modelNew, pairwise ~ category): gives you marginal means for each level of the fixed effect factor & pairwise comparisons among levels of the factor
# emmeans(modelNew, 'category', type='response'): gives you probabilities for each level of the fixed effect factor
# emmeans(modelOld1, pairwise ~ category, lmer.df = "satterthwaite"): gives you probabilities for each fixed effect and odds ratios + p-values for pairwise comparisons among levels of the fixed effect factor


# test for meeting assumption of proportional odds
# data_old$category <-  factor(data_old$category, levels = c('Social Norms', 'Care-Emo', 'Care-Phys', 'Fairness', 'Loyalty', 'Authority', 'Purity', 'Liberty')) # re-l evel category so that Social Norms is the intercept
# modelMoral.clm <- clm(moral_decision ~ category + subID, data = data_old)
# nominal_test(modelMoral.clm)
# scale_test(modelMoral.clm) # failed both tests (highly significant, p < 2.2e-16)

# partial proportional odds using vcrpart -- didn't fit
# modelMoral.olmm <- olmm(as.factor(moral_decision) ~ ce(category) + re(1 + category | subID), data = data_old, 
#                         family = cumulative(link = 'logit'))

# partial proportional odds using mixor -- didn't fit
# modelMoral.mix <- mixor(moral_decision ~ category, data = data_old, id = subID, KG=1, link = 'logit')

# Bayesian Generalized Linear Multivariate Multilevel Model (probably not gonna use but keeping the code here just in case)
# modelMoral <- brm(moral_decision ~ category + (1 + category | subID) + (1 | vigfile), 
#                   family=cumulative(link="logit", threshold="flexible"), data=data_old, cores=4, file='mftMoralDecision')
# summary(modelMoral)
# conditional_effects(modelMoral)
# conditional_effects(modelMoral, categorical=TRUE)

```

```{r Tidy questionnaires, include=FALSE}

# load qualtrics
foundation_matching <- read.csv('data/behavior/qualtrics/foundation_matching.csv', stringsAsFactors = FALSE)
all_other_surveys <- read.csv('data/behavior/qualtrics/all_other_surveys.csv', stringsAsFactors = FALSE)

# score MFQ
mfq <- select(all_other_surveys, starts_with('sub'), starts_with('mfq'))
#part one
mfq[mfq == 'Not at all relevant' ] <- 0
mfq[mfq == 'Not very relevant' ] <- 1
mfq[mfq == 'Slightly relevant' ] <- 2
mfq[mfq == 'Somewhat relevant' ] <- 3
mfq[mfq == 'Very relevant' ] <- 4
mfq[mfq == 'Extremely relevant' ] <- 5
#part two
mfq[mfq == 'Strongly disagree' ] <- 0
mfq[mfq == 'Moderately disagree' ] <- 1
mfq[mfq == 'Slightly disagree' ] <- 2
mfq[mfq == 'Slightly agree' ] <- 3
mfq[mfq == 'Moderately agree' ] <- 4
mfq[mfq == 'Strongly agree' ] <- 5
# compute results
colnames(mfq) <- substr(colnames(mfq), 5, 7)
names(mfq)[1] <- 'subID'
mfq <- mfq[-1,]
mfq[,2:33] <- as.numeric(unlist(mfq[,2:33]))
mfq <- mfq %>% mutate(careScore = rowSums(select(., c('1','7','12','17','23','28')), na.rm = TRUE),
                     fairnessScore = rowSums(select(., c('2','8','13','18','24','29')), na.rm = TRUE),
                     loyaltyScore = rowSums(select(., c('3','9','14','19','25','30')), na.rm = TRUE),
                     authorityScore = rowSums(select(., c('4','10','15','20','26','31')), na.rm = TRUE),
                     purityScore = rowSums(select(., c('5','11','16','21','27','32')), na.rm = TRUE),
                     subID = as.numeric(subID)) %>%
  filter(subID != 20, subID %in% dataSubs)
# write table 
qualtrics_means <- mfq %>% select(contains('Score')) %>%
  summarise(careMean = mean(careScore),
            careSD = sd(careScore),
            fairnessMean = mean(fairnessScore),
            fairnessSD = sd(fairnessScore),
            loyaltyMean = mean(loyaltyScore),
            loyaltySD = sd(loyaltyScore),
            authorityMean = mean(authorityScore),
            authoritySD = sd(authorityScore),
            purityMean = mean(purityScore),
            puritySD = sd(purityScore))

# score disgust_scale
disgust_scale <- select(all_other_surveys, starts_with('sub'), starts_with('disgust'))
#part one
disgust_scale[disgust_scale == 'Strongly disagree' ] <- 0
disgust_scale[disgust_scale == 'Mildly disagree' ] <- 1
disgust_scale[disgust_scale == 'Neither agree nor disagree' ] <- 2
disgust_scale[disgust_scale == 'Mildly agree' ] <- 3
disgust_scale[disgust_scale == 'Strongly agree' ] <- 4
#part two
disgust_scale[disgust_scale == 'Not disgusting at all' ] <- 0
disgust_scale[disgust_scale == 'Slightly disgusting' ] <- 1
disgust_scale[disgust_scale == 'Moderately disgusting' ] <- 2
disgust_scale[disgust_scale == 'Very disgusting' ] <- 3
disgust_scale[disgust_scale == 'Extremely disgusting' ] <- 4
# compute results
colnames(disgust_scale) <- as.character(c('subID', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27))
disgust_scores <- select(disgust_scale, -'12', -'16') #get rid of catch questions
disgust_scores <- as.data.frame(disgust_scores[-1,])  %>%
  mutate(subID = as.numeric(subID)) %>%
  filter(subID != 20, subID %in% dataSubs)
disgust_scores[,2:25] <- as.numeric(unlist(disgust_scores[,2:25]))
reverse4 <- function(x) 4 - x
disgust_scores[,c('1','6','10')] <- reverse4(disgust_scores[,c('1','6','10')])
disgust_scores$score <- rowSums(disgust_scores[2:25])
disgust_mean <- disgust_scores %>% 
  summarise(disgustMean = mean(score),
            disgustSD = sd(score))
qualtrics_means <- cbind(qualtrics_means, disgust_mean)


# # score secs - conservatism increases with score
secs <- select(all_other_surveys, starts_with('sub'), starts_with('secs'))
colnames(secs) <- substr(colnames(secs), 6, 8)
names(secs)[1] <- 'subID'
secs <- secs[-1,]
secs[,2:13] <- as.numeric(unlist(secs[,2:13]))
social <- c('1','3','4','7','8','11','12')
economic <- c('2', '5', '6', '9', '10')
reverse100 <- function(x) 100 - x
reverseScoredSECS <- c('1', '5')
secs[,reverseScoredSECS] <- reverse100(secs[,reverseScoredSECS])
secs <- secs %>% 
  mutate(SocialConservatism = rowMeans(select(., social), na.rm = TRUE),
         EconomicConservatism = rowMeans(select(., economic), na.rm = TRUE),
         subID = as.numeric(subID)) %>%
  filter(subID != 20, subID %in% dataSubs)

secs_means <- secs %>%
  summarise(socialConservatismMean = mean(SocialConservatism),
            socialConservatismSD = sd(SocialConservatism),
            economicConservatismMean = mean(EconomicConservatism),
            economicConservatismSD = sd(EconomicConservatism))

qualtrics_means <- cbind(qualtrics_means, secs_means)
qualtrics_means <- pivot_longer(qualtrics_means, cols = 1:ncol(qualtrics_means), names_to = 'Measure', values_to = 'Value') %>%
  mutate(Value = round(Value, 2))
write.csv(qualtrics_means, file = 'figures/paper/table_qualtricsMeans.csv', row.names = F)
```

```{r em_int_moral summary stuff}
# compute effect sizes
# em_category.cov <- list(angry=0, amused=0, sad=0, afraid=0, contemptuous=0, disgusted=0, 
#                         PersonalDistressScore=0, EmpathicConcernScore=0, 
#                         PerspectiveTakingScore=0, FantasyScore=0)
# 
# emmeans(em_category, ~ category, at=em_category.cov) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'eff')
# 
# emmeans(em_category, ~ angry, at=list_modify(em_category.cov, angry=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ amused, at=list_modify(em_category.cov, amused=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# em_categorySad <- emmeans(em_category, ~ sad, at=list_modify(em_category.cov, sad=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ afraid, at=list_modify(em_category.cov, afraid=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ contemptuous, at=list_modify(em_category.cov, contemptuous=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ disgusted, at=list_modify(em_category.cov, disgusted=c(0,1))) %>% 
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ PersonalDistressScore, at=list_modify(em_category.cov, PersonalDistressScore=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ EmpathicConcernScore, at=list_modify(em_category.cov, EmpathicConcernScore=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ PerspectiveTakingScore, at=list_modify(em_category.cov, PerspectiveTakingScore=c(0,1))) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ FantasyScore, at=list_modify(em_category.cov, FantasyScore=c(0,1))) %>% 
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'revpairwise')
# 
# emmeans(em_category, ~ angry * category, at=list_modify(em_category.cov, angry=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ amused * category, at=list_modify(em_category.cov, amused=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ sad * category, at=list_modify(em_category.cov, sad=c(0,1))) %>%
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ afraid * category, at=list_modify(em_category.cov, afraid=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ afraid * category, at=list_modify(em_category.cov, afraid=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ contemptuous * category, at=list_modify(em_category.cov, contemptuous=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ disgusted * category, at=list_modify(em_category.cov, disgusted=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ PersonalDistressScore * category, at=list_modify(em_category.cov, PersonalDistressScore=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ EmpathicConcernScore * category, at=list_modify(em_category.cov, EmpathicConcernScore=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ PerspectiveTakingScore * category, at=list_modify(em_category.cov, PerspectiveTakingScore=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')
# 
# emmeans(em_category, ~ FantasyScore * category, at=list_modify(em_category.cov, FantasyScore=c(0,1))) %>% 
#   contrast(interaction=c('revpairwise', 'eff')) %>%
#   eff_size(sigma = sd(em_compare$moral_decision), edf = df.residual(em_category), method = 'identity')

### compute lines for plotting
# em_range <- function(emotion, precision=0.5) {
#   return(seq(min(em_compare[,emotion], na.rm=TRUE),
#              max(em_compare[,emotion], na.rm=TRUE),
#              precision))
# }
# 
# # make dfs for plotting
# anger_trends <- as.data.frame(emmeans(em_category, ~ angry | category, at=list(angry=em_range('angry'))))
# anger_effect <- as.data.frame(emmeans(em_category, ~ angry, at=list(angry=em_range('angry'))))
# anger.emt <- emtrends(em_category, ~ category, 'angry')
# 
# amusement_trends <- as.data.frame(emmeans(em_category, ~ amused | category, at=list(amused=em_range('amused'))))
# amusement_effect <- as.data.frame(emmeans(em_category, ~ amused, at=list(amused=em_range('amused'))))
# amusement.emt <- emtrends(em_category, ~ category, 'amused')
# 
# sadness_trends <- as.data.frame(emmeans(em_category, ~ sad | category, at=list(sad=em_range('sad'))))
# sadness_effect <- as.data.frame(emmeans(em_category, ~ sad, at=list(sad=em_range('sad'))))
# sadness.emt <- emtrends(em_category, ~ category, 'sad')
# 
# fear_trends <- as.data.frame(emmeans(em_category, ~ afraid | category, at=list(afraid=em_range('afraid'))))
# fear_effect <- as.data.frame(emmeans(em_category, ~ afraid, at=list(afraid=em_range('afraid'))))
# fear.emt <- emtrends(em_category, ~ category, 'afraid')
# 
# contempt_trends <- as.data.frame(emmeans(em_category, ~ contemptuous | category, at=list(contemptuous=em_range('contemptuous'))))
# contempt_effect <- as.data.frame(emmeans(em_category, ~ contemptuous, at=list(contemptuous=em_range('contemptuous'))))
# contempt.emt <- emtrends(em_category, ~ category, 'contemptuous')
# 
# disgust_trends <- as.data.frame(emmeans(em_category, ~ disgusted | category, at=list(disgusted=em_range('disgusted'))))
# disgust_effect <- as.data.frame(emmeans(em_category, ~ disgusted, at=list(disgusted=em_range('disgusted'))))
# disgust.emt <- emtrends(em_category, ~ category, 'disgusted')
# 
# personalDistress_trends <- as.data.frame(emmeans(em_category, ~ PersonalDistressScore | category, at=list(PersonalDistressScore=em_range('PersonalDistressScore'))))
# personalDistress_effect <- as.data.frame(emmeans(em_category, ~ PersonalDistressScore, at=list(PersonalDistressScore=em_range('PersonalDistressScore'))))
# PD.emt <- emtrends(em_category, ~ category, 'PersonalDistressScore')
# 
# empathicConcern_trends <- as.data.frame(emmeans(em_category, ~ EmpathicConcernScore | category, at=list(EmpathicConcernScore=em_range('EmpathicConcernScore'))))
# empathicConcern_effect <- as.data.frame(emmeans(em_category, ~ EmpathicConcernScore, at=list(EmpathicConcernScore=em_range('EmpathicConcernScore'))))
# EC.emt <- emtrends(em_category, ~ category, 'EmpathicConcernScore')
# 
# perspectiveTaking_trends <- as.data.frame(emmeans(em_category, ~ PerspectiveTakingScore | category, at=list(PerspectiveTakingScore=em_range('PerspectiveTakingScore'))))
# perspectiveTaking_effect <- as.data.frame(emmeans(em_category, ~ PerspectiveTakingScore, at=list(PerspectiveTakingScore=em_range('PerspectiveTakingScore'))))
# PT.emt <- emtrends(em_category, ~ category, 'PerspectiveTakingScore')
# 
# fantasy_trends <- as.data.frame(emmeans(em_category, ~ FantasyScore | category, at=list(FantasyScore=em_range('FantasyScore'))))
# fantasy_effect <- as.data.frame(emmeans(em_category, ~ FantasyScore, at=list(FantasyScore=em_range('FantasyScore'))))
# fantasy.emt <- emtrends(em_category, ~ category, 'FantasyScore')

#### plot
# ggplot(anger_trends, aes(x=angry, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = anger_effect) +
#   geom_ribbon(data = anger_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Anger Score (scaled)', tag = 'A.', title = 'Anger') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_anger.png', dpi = 300, width = 13, height = 3.5)
# contrast(anger.emt, adjust = 'none')
# 
# ggplot(amusement_trends, aes(x=amused, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = amusement_effect) +
#   geom_ribbon(data = amusement_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Amusement Score (scaled)', tag = 'B.', title = 'Amusement') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_amusement.png', width=13, height = 3.5, dpi = 300)
# contrast(amusement.emt, adjust = 'none')
# 
# 
# ggplot(sadness_trends, aes(x=sad, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = sadness_effect) +
#   geom_ribbon(data = sadness_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Sadness Score (scaled)', tag = 'C.', title = 'Sadness') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_sadness.png', width = 13, height = 3.5, dpi = 300)
# contrast(sadness.emt, adjust = 'none')
# 
# ggplot(fear_trends, aes(x=afraid, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = fear_effect) +
#   geom_ribbon(data = fear_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Fear Score (scaled)', tag = 'D.', title = 'Fear') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_fear.png', width = 13, height = 3.5, dpi = 300)
# contrast(fear.emt, adjust = 'none')
# 
# ggplot(contempt_trends, aes(x=contemptuous, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = contempt_effect) +
#   geom_ribbon(data = contempt_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Contempt Score (scaled)', tag = 'E.', title = 'Contempt') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_contempt.png', width = 13, height = 3.5, dpi = 300)
# contrast(contempt.emt, adjust = 'none')
# 
# ggplot(disgust_trends, aes(x=disgusted, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = disgust_effect) +
#   geom_ribbon(data = disgust_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Disgust Score (scaled)', tag = 'F.', title = 'Disgust') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_disgust.png', width = 13, height = 3.5, dpi = 300)
# contrast(disgust.emt, adjust = 'none')
# 
# ggplot(personalDistress_trends, aes(x=PersonalDistressScore, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = personalDistress_effect) +
#   geom_ribbon(data = personalDistress_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Personal Distress Score (scaled)', tag = 'G.', title = 'Personal Distress') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_personalDistress.png', width = 13, height = 3.5, dpi = 300)
# contrast(PD.emt, adjust = 'none')
# 
# ggplot(empathicConcern_trends, aes(x=EmpathicConcernScore, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = empathicConcern_effect) +
#   geom_ribbon(data = empathicConcern_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Empathic Concern Score (scaled)', tag = 'H.', title = 'Empathic Concern') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_empathicConcern.png', width = 13, height = 3.5, dpi = 300)
# contrast(EC.emt, adjust = 'none')
# 
# ggplot(perspectiveTaking_trends, aes(x=PerspectiveTakingScore, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = perspectiveTaking_effect) +
#   geom_ribbon(data = perspectiveTaking_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Perspective Taking Score (scaled)', tag = 'I.', title = 'Perspective Taking') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_perspectiveTaking.png', width = 13, height = 3.5, dpi = 300)
# contrast(PT.emt, adjust = 'none')
# 
# ggplot(fantasy_trends, aes(x=FantasyScore, y=emmean,ymin=lower.CL, ymax=upper.CL)) +
#   geom_line(data = fantasy_effect) +
#   geom_ribbon(data = fantasy_effect, alpha = 0.2) +
#   geom_line(aes(color=category)) +
#   geom_ribbon(aes(fill=category), alpha=0.3) +
#   facet_grid(. ~ category) +
#   MFT_color() + MFT_fill() +
#   theme_pubr(legend = 'none') +
#   labs(y='Moral judgment', x='Fantasy Score (scaled)', tag = 'J.', title = 'Fantasy') +
#   theme(axis.text = element_text(size=10),
#         plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
#         strip.background = element_rect(color = 'black', fill='gray99', size = 0.25),
#         strip.text = element_text(face = 'bold', size = 12),
#         panel.border = element_rect(colour = 'black', fill = NA, size = 0.25),
#         axis.line = element_line(size = 0.25),
#         text = element_text(family = 'Times New Roman'))
# ggsave('figures/paper/plot_fantasy.png', width = 13, height = 3.5, dpi = 300)
# contrast(fantasy.emt, adjust = 'none')
```
